### ISSUE TITLE
Use Windows Integrated Authentication

### ISSUE THREAD

**Issue by juancentro** [agstudy/rsqlserver#14]
Is it possible to use the user Windows credentials to log on to the server? By specifiyng the connection string directly it should be possible theoretically

**Comment by jangorecki** [comment]
Answer to your question seems to be available here: https://github.com/agstudy/rsqlserver/wiki/benchmarking
search for:
> In the other side `rsqlserver` offer many ways to acces to the data base.
but I haven't test it.

**Comment by juancentro** [comment]
I've tested and it works! Great!
