### ISSUE TITLE
Interpret quotes

### ISSUE THREAD

**Issue by wibeasley** [agstudy/rsqlserver#18]
Is there a way to have the bulk copy mechanism interpret the quotes surrounding character fields, and not upload them to the database.  (For my current situation, I could just [unquote the temp csv](https://github.com/agstudy/rsqlserver/pull/17), but I'm hoping there's a more general solution in case the quotes are necessary to handle commas inside the actual values.)

In other words, instead of the default bulk copy resulting in something like this

![image](https://cloud.githubusercontent.com/assets/1372890/7899518/b006124a-06eb-11e5-94b1-455a508e3e67.png)
 it would look like this:
![image](https://cloud.githubusercontent.com/assets/1372890/7899525/ec7c2b88-06eb-11e5-8fa7-0a1d5ef2c319.png)

I see that `clrCallStatic("rsqlserver.net.misc","SqlBulkCopy",con.string ,value,name)` is called underneath, and you've mentioned the [bcp utility](http://stackoverflow.com/questions/14334840/how-to-insert-a-dataframe-into-a-sql-server-table) in other posts, but I didn't understand how they fit together.  Is this a simple configuration change?

**Comment by agstudy** [comment]
Using `Quote=FALSE` fix the problem?

**Comment by wibeasley** [comment]
That option worked for my specific scenario (which prompted PR #17), but I think always including the quotes is an overall undesirable behavior because

1. It's almost never desired to have quotes around text fields after it's written to the database.  Those quotes are mostly so the CSV columns don't get confused if a text field contains a comma.  SQL WHERE clauses are much more natural as `WHERE FindingCategory='Bad'` than `WHERE FindingCategory='"Bad"'`.
1. Sometimes there's a legitimate need to use quotes for that intermediate file saved (on the local machine before the bulk upload occurs).  Like when a text field contains a comma (eg an address).

I don't understand the details of the underlying chain using bcp and `clCallStatic`.  I was hoping those developers had encountered this problem before, and had some option like "IgnoreQuotesDuringUpload".

**Comment by wibeasley** [comment]
Thanks @agstudy for all your work on this package.  It saves us so much time (over RODBC) with our warehouse-ish projects.

**Comment by agstudy** [comment]
Since the end of this year , I will come back to this package to work on it actively and use it as a component from our consulting services.

**Comment by wibeasley** [comment]
Great.  I just sent you an invitation on LinkedIn.  Contact me when it's best for you, and I'm happy to help.
