### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by ruaridhw** [agstudy/rsqlserver#29]
Build a Docker image that can be used to run the package on macOS, Linux and Windows in a self-contained environment.

Relates to #24 #16 #13 

- [x]  Build Docker image that inherits from rocker/r-ver + devtools + rClr
- [x]  Write setup script `docker.sh` for easy installation and use of images
- [x]  Add RStudio build instructions to `docker.sh`
- [ ]  Retune `docker.sh` using [compose](https://docs.docker.com/compose/overview/#compose-documentation) to avoid manually starting multiple containers

**Comment by ruaridhw** [comment]
The documentation for Linux and Windows also needs a refresh as there are several known issues  with rClr on Mono and newer versions of .NET for Windows.

See jmp75/rClr#27 and jmp75/rClr#31 for rClr build errors on Linux and macOS

**Comment by agstudy** [comment]
Excellent idea! I will try to help on this.

**Comment by agstudy** [comment]
Excellent. That was very fast. Excellent.

**Comment by ruaridhw** [comment]
@agstudy would you like to test the [docker help script](https://github.com/agstudy/rsqlserver/blob/master/docker.sh) so that it's easy enough to follow along?

Also, if you prefer using RStudio Server for interactivity over CLI R, you can download [these two files](https://github.com/ruaridhw/dockerfiles/tree/master/rsqlserver/rstudio) and in `docker.sh` run:

`docker build -t rsqlserver-rstudio .` instead of `docker pull ruaridhw/rsqlserver:latest`

and replace `rsqlserver-rstudio` everywhere there is `ruaridhw/rsqlserver`

Probably best to test both cases.

- [ ]  Add RStudio build instructions to `docker.sh`

**Comment by agstudy** [comment]
I have tested the docker.sh. 

I think it works , but I am not sure becuase I don't know how to test it now.
PS I have added me as a docker user: ` sudo usermod -aG docker $USER`

**Comment by ruaridhw** [comment]
Sorry, I just mean trial them so it's easy to understand and works as expected. You can run both images together or independently:

1. You can trial both images separately by just running the R session interactively and issuing any commands you like. The SQL Server image can be connected at ` host = localhost` from any desktop client.

2. Run the R session interactively (the last section) and `library(rsqlserver)` in your session. Then you can connect to the DB image with `con <- dbConnect('SqlServer', host = 'mydb', dbname = 'rsqlserverdb', user = 'SA', password = 'P@ssw0rd1')` as per the second last part.

**Comment by agstudy** [comment]
I tested the 2 last statements:

```
docker run --name testrsqlserver --link=mssqldb --rm ruaridhw/rsqlserver Rscript \
   -e "library(rsqlserver)" \
   -e "con <- dbConnect('SqlServer', host = 'mydb', dbname = 'rsqlserverdb', user = 'SA', password = 'P@ssw0rd1')" \
   -e "dbReadTable(con, 'Inventory')"
```

Works fine and give the expecte dresult : 
```

  id   name quantity
1  1 banana      150
2  2 orange      154
```
Then I tested the intercative R session and it works fine also: 

```
docker rm rsqlserver122
docker run --name rsqlserver122 --link=mssqldb -i ruaridhw/rsqlserver


```
Excellent job!

**Comment by agstudy** [comment]
Now, How I can call the rsqlserver from Rstudio session?

**Comment by ruaridhw** [comment]
Do you mean your local RStudio installation? It's exactly as on the R image:

```
con <- dbConnect('SqlServer', host = 'mydb', dbname = 'rsqlserverdb', user = 'SA', password = 'P@ssw0rd1')
```

Since I'm on a Mac, I can't run *rsqlserver* on my local RStudio so I have to run RStudio Server on a Docker image. That's what I was referring to [here](https://github.com/agstudy/rsqlserver/issues/29#issuecomment-338456786)
