### ISSUE TITLE
releasing a minor update on local computer

### ISSUE THREAD

**Issue by sun0HnnN4475de8ZIZLG** [agstudy/rsqlserver#40]
I am trying to test a minor update to rsqlserver locally, but am unsure what files I need to replace.

I compiled the project creating a new version of rsqlserver.net in rsqlserver-master\src.nocompile\rsqlserver.net\bin\Release and then I copied this to C:\Program Files\Microsoft\R Open\R-3.4.2\library\rsqlserver\libs

I am still getting an error message referring to C:\Users\Ruaridh Williamson\Documents\GitHub\rsqlserver\src.nocompile\rsqlserver.net\src\SqlDataHelper.cs,
so I suspect that I need to replace some other file.

Do you have an idea what files I need to replace to release an update locally?

Thank you

**Comment by sun0HnnN4475de8ZIZLG** [comment]
never mind, with a larger search I found out the dll had to be replaced in C:\Users\username\Documents\R\win-library\3.4\rsqlserver\libs instead

Now I can test a tweak that I wanted to try, will let you know if it helps.

**Comment by ruaridhw** [comment]
Yes, that's right.

The dlls are included in the package pre-compiled in the `inst/libs` folder. My understanding is this isn't great practice and is why the error messages refer to source code hardcoded to my computer's path.

You've already worked this out but to recompile the entire package, you run `xbuild` on the .NET solution and then copy the dlls across to `inst/libs` before building the R package.

This used to be achieved with [install.libs.R](https://github.com/agstudy/rsqlserver/blob/843266d01d55eacc93300aa79a144ea5bd2fe0f7/src.nocompile/install.libs.R)
