### ISSUE TITLE
linux support question

### ISSUE THREAD

**Issue by jangorecki** [agstudy/rsqlserver#9]
Any future plans to support linux?

If no, maybe some recommendation for high performance MSSQL connection from R on linux?
doesn't have to be DBI compliant.
Regards

**Comment by jangorecki** [comment]
reopening, would be nice to get an update from @agstudy

**Comment by agstudy** [comment]
Sorry to not answer before. For financial problems, I can't work on this package for the moment. 
Any help is welcome( coding this part or donation)

**Comment by agstudy** [comment]
Mono version is available now.  It is under tests and 90 % percent of functionalities works fine.

**Comment by jangorecki** [comment]
Don't have sql server now to do my tests. Once I will have one I will try it. Would be much easier if sql server would be available for ubuntu :)

**Comment by agstudy** [comment]
:) Maybe you can try with Sybase ( I am not sure the they use the same mono interface for 2 data bases). That's said , I am using a virtual machine , install windows ans SQL server express edition.
